# Generated by Django 3.2.9 on 2021-12-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexp',
            name='icon',
        ),
        migrations.AddField(
            model_name='workexp',
            name='img',
            field=models.ImageField(blank=True, upload_to='workexp/'),
        ),
    ]
