# Generated by Django 3.2.9 on 2021-12-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211205_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='icon',
        ),
        migrations.AddField(
            model_name='education',
            name='img',
            field=models.ImageField(blank=True, upload_to='workexp/'),
        ),
    ]
