# Generated by Django 3.2.9 on 2021-12-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20211205_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='color',
            field=models.CharField(default='white', max_length=30),
        ),
        migrations.AlterField(
            model_name='languages',
            name='color',
            field=models.CharField(default='white', max_length=30),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='color',
            field=models.CharField(default='white', max_length=30),
        ),
    ]
